/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JOBXPembelajaran;
import java.awt.Color;
import static java.awt.event.KeyEvent.VK_ESCAPE;
import java.io.BufferedInputStream;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.*;
/**
 *
 * @author mh4nx7net
 */

public class Pembelajaran extends javax.swing.JFrame {

    /**
     * Creates new form Pembelajaran
     */
    
    ImageIcon icon = new ImageIcon(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/icoakun.png"));
    public Pembelajaran() {
        initComponents();
        setBackground(new Color(0,0,153,90));
        setIconImage(icon.getImage());
        setTitle("Pembelajaran");
        setLocationRelativeTo(null);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        cben = new javax.swing.JCheckBox();
        cbjp = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        cbid = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 153));
        setUndecorated(true);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(30, 30, 30));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanel1KeyReleased(evt);
            }
        });
        jPanel1.setLayout(null);

        jButton8.setBackground(new java.awt.Color(255, 102, 102));
        jButton8.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("8");
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(110, 130, 40, 50);

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("2");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(60, 70, 40, 50);

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("3");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(110, 70, 40, 50);

        jButton5.setBackground(new java.awt.Color(255, 102, 102));
        jButton5.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("5");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(210, 70, 40, 50);

        jButton10.setBackground(new java.awt.Color(255, 102, 102));
        jButton10.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("9");
        jButton10.setBorder(null);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(160, 130, 40, 50);

        jButton6.setBackground(new java.awt.Color(255, 102, 102));
        jButton6.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("6");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(10, 130, 40, 50);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("1");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 70, 40, 50);

        jButton7.setBackground(new java.awt.Color(255, 102, 102));
        jButton7.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("7");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(60, 130, 40, 50);

        jButton4.setBackground(new java.awt.Color(255, 102, 102));
        jButton4.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("4");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(160, 70, 40, 50);

        jButton9.setBackground(new java.awt.Color(255, 102, 102));
        jButton9.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("0");
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(210, 130, 40, 50);

        cben.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(cben);
        cben.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cben.setForeground(new java.awt.Color(255, 255, 255));
        cben.setText("ENGLISH");
        cben.setBorder(null);
        cben.setOpaque(false);
        jPanel1.add(cben);
        cben.setBounds(260, 140, 90, 20);

        cbjp.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(cbjp);
        cbjp.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbjp.setForeground(new java.awt.Color(255, 255, 255));
        cbjp.setText(" 日本");
        cbjp.setBorder(null);
        cbjp.setOpaque(false);
        jPanel1.add(cbjp);
        cbjp.setBounds(260, 120, 90, 20);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("esc for exit");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 240, 69, 15);

        cbid.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(cbid);
        cbid.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbid.setForeground(new java.awt.Color(255, 255, 255));
        cbid.setText("INDONESIA");
        cbid.setBorder(null);
        cbid.setOpaque(false);
        jPanel1.add(cbid);
        cbid.setBounds(260, 160, 90, 20);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 30, 30));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("have a nice day");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(240, 230, 100, 20);

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 30, 30));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("cuma mau bilang");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(210, 190, 130, 20);

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 30, 30));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("salah satu dari tombol adalah virus");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 210, 230, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JOBXPembelajaran/basis/icoakun.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(280, 10, 80, 100);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 16, 379, 280));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PENGENALAN ANGKA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (cbid.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/1.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        if (cben.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/11.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        if (cbjp.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/111.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        else if (!cbid.isSelected()&&!cben.isSelected()&&!cbjp.isSelected())
        {
            JOptionPane.showMessageDialog(null, "Please Select One of the Language");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (cbid.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/2.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        if (cben.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/22.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        if (cbjp.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/222.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        else if (!cbid.isSelected()&&!cben.isSelected()&&!cbjp.isSelected())
        {
            JOptionPane.showMessageDialog(null, "Please Select One of the Language");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (cbid.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/3.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        if (cben.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/33.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        if (cbjp.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/333.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        else if (!cbid.isSelected()&&!cben.isSelected()&&!cbjp.isSelected())
        {
            JOptionPane.showMessageDialog(null, "Please Select One of the Language");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (cbid.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/4.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        if (cben.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/44.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        if (cbjp.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/444.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        else if (!cbid.isSelected()&&!cben.isSelected()&&!cbjp.isSelected())
        {
            JOptionPane.showMessageDialog(null, "Please Select One of the Language");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (cbid.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/5.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        if (cben.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/55.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        if (cbjp.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/555.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        else if (!cbid.isSelected()&&!cben.isSelected()&&!cbjp.isSelected())
        {
            JOptionPane.showMessageDialog(null, "Please Select One of the Language");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
                if (evt.getKeyCode()==VK_ESCAPE)
        {
            System.out.print("metu goblok");
        }
    }//GEN-LAST:event_formKeyTyped

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (cbid.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/6.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        if (cben.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/66.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        if (cbjp.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/666.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        else if (!cbid.isSelected()&&!cben.isSelected()&&!cbjp.isSelected())
        {
            JOptionPane.showMessageDialog(null, "Please Select One of the Language");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (cbid.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/7.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        if (cben.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/77.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        if (cbjp.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/777.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        else if (!cbid.isSelected()&&!cben.isSelected()&&!cbjp.isSelected())
        {
            JOptionPane.showMessageDialog(null, "Please Select One of the Language");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if (cbid.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/8.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        if (cben.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/88.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        if (cbjp.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/888.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        else if (!cbid.isSelected()&&!cben.isSelected()&&!cbjp.isSelected())
        {
            JOptionPane.showMessageDialog(null, "Please Select One of the Language");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        if (cbid.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/9.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        if (cben.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/99.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        if (cbjp.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/999.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        else if (!cbid.isSelected()&&!cben.isSelected()&&!cbjp.isSelected())
        {
            JOptionPane.showMessageDialog(null, "Please Select One of the Language");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if (cbid.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/0.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        if (cben.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/00.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        if (cbjp.isSelected())
        {
            try {
            new Player(new BufferedInputStream(Pembelajaran.class.getResource("/JOBXPembelajaran/basis/000.mp3").openStream())).play(30);
        }
        catch (IOException | JavaLayerException e){
            System.out.print("Error goblok, onok sek kurang");
        }
        }
        else if (!cbid.isSelected()&&!cben.isSelected()&&!cbjp.isSelected())
        {
            JOptionPane.showMessageDialog(null, "Please Select One of the Language");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseReleased

    private void jPanel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode()==VK_ESCAPE)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jPanel1KeyReleased

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        jLabel4.setForeground(new Color(255,102,102));
        jLabel5.setForeground(new Color(255,102,102));
        jLabel3.setForeground(new Color(255,102,102));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        jLabel4.setForeground(new Color(30,30,30));
        jLabel5.setForeground(new Color(30,30,30));
        jLabel3.setForeground(new Color(30,30,30));
        JOptionPane.showMessageDialog(null, "ehehehe");
    }//GEN-LAST:event_jLabel4MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembelajaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Pembelajaran().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cben;
    private javax.swing.JCheckBox cbid;
    private javax.swing.JCheckBox cbjp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
